maintainer       "Ubilabs GmbH"
maintainer_email "mueller@ubilabs.net"
license          "Apache 2.0"
description      "Installs delayed_job dependencies"
version          "0.0.1"
recipe           "monit", "Installs monit config for delayed_job"
